In [1]:
import numpy as np
import math

L, d_k, d_v = 4, 8, 8
q = np.random.rand(L, d_k)
k = np.random.rand(L, d_k)
v = np.random.rand(L, d_v)


In [2]:
print(q)

[[0.66591486 0.483948   0.65703501 0.721948   0.17725997 0.51621955
  0.97681684 0.475921  ]
 [0.48831311 0.73694313 0.47870875 0.66093019 0.00493228 0.26488002
  0.8526982  0.37341833]
 [0.33759034 0.09187206 0.49272245 0.3884394  0.70561116 0.88169714
  0.13264123 0.59026759]
 [0.03745709 0.18262709 0.16794478 0.91068081 0.5257054  0.82724924
  0.79392561 0.06423781]]


self_attention = softmax(((Q.K[transpose])/root(d_k))+M)V

In [3]:
np.matmul(q ,k.T)

array([[2.50286248, 3.18433483, 2.63678171, 2.91414775],
       [2.01129534, 2.79715023, 2.09728104, 2.23858287],
       [1.79402911, 1.73741309, 1.99445345, 2.14089526],
       [1.89489531, 1.93088542, 2.18606139, 2.17681919]])

In [4]:
# why we need sqrt(d_k) in the denominator
q.var() , k.var() , np.matmul(q ,k.T).var()

(0.07712972083544284, 0.07472497390855894, 0.16807017742833866)

In [5]:
scaled = np.matmul(q ,k.T) / math.sqrt(d_k)
q.var() , k.var() , scaled.var()

(0.07712972083544284, 0.07472497390855894, 0.021008772178542332)

In [6]:
scaled

array([[0.88489552, 1.12583238, 0.93224311, 1.03030682],
       [0.71110029, 0.98894195, 0.74150082, 0.79145857],
       [0.63428507, 0.61426829, 0.70514578, 0.75692078],
       [0.66994666, 0.68267109, 0.77288941, 0.76962181]])

Masking


In [7]:
mask =np.tril(np.ones((L, L)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [8]:
mask[mask==0] = -np.infty
mask[mask==1] = 0

In [9]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [10]:
scaled + mask

array([[0.88489552,       -inf,       -inf,       -inf],
       [0.71110029, 0.98894195,       -inf,       -inf],
       [0.63428507, 0.61426829, 0.70514578,       -inf],
       [0.66994666, 0.68267109, 0.77288941, 0.76962181]])

In [17]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1) 

In [20]:
attention = softmax(scaled + mask)

In [21]:
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.84046898, 0.569017  , 0.        , 0.        ],
       [0.77832551, 0.39120693, 0.35152829, 0.        ],
       [0.80658269, 0.41890303, 0.37616724, 0.26142925]])

In [22]:
new_v = np.matmul(attention, v)
new_v

array([[0.55545062, 0.1646575 , 0.56371012, 0.56949148, 0.77494086,
        0.4534436 , 0.49482337, 0.08151995],
       [0.60373054, 0.61888512, 0.84740522, 0.75553145, 0.94350658,
        0.54230964, 0.96211589, 0.55314926],
       [0.70944205, 0.47550427, 0.69860588, 0.84541619, 1.10711394,
        0.70736308, 1.09474389, 0.43466857],
       [0.97350506, 0.70859173, 0.91836904, 0.92245965, 1.28516033,
        0.92953447, 1.28715496, 0.56918863]])